services:
  ollama:
    build:
      context: ./ollama
    image: gajesh/ollama-requirements-classifier:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
